service: daily-weather

provider:
  name: aws
  runtime: nodejs8.10

functions:
  joker:
    handler: handler.weather
    events:
      - schedule: cron(0 8 * * 1-5)
    environment:
      SLACK_WEBHOOK_URL: https://hooks.slack.com/services/.../.../...
